kind: pipeline
type: ssh
name: deploy_prod_backend

server:
  host:
    from_secret: ssh_host_prod
  user: root
  password:
    from_secret: ssh_password_prod

steps:
  - name: deploy-tobi
    environment:
      loki_sink:
        from_secret: loki_sink
      PF_SECRETS:
        from_secret: pf_secrets
      COMPOSE_PROJECT_NAME: webservices
    commands:
      - docker compose -f PortfolioApi/docker-compose_tobi.yaml build
      - docker compose -f PortfolioApi/docker-compose_tobi.yaml up -d
  - name: deploy-claes
    environment:
      loki_sink:
        from_secret: loki_sink
      PF_SECRETS:
        from_secret: pf_secrets_claes
      COMPOSE_PROJECT_NAME: webservices
    commands:
      - docker compose -f PortfolioApi/docker-compose_claes.yaml build
      - docker compose -f PortfolioApi/docker-compose_claes.yaml up -d

trigger:
  branch:
    - master
  event:
    - push

